const Sequelize = require("sequelize");
const sequelize = require('./sequelize').sequelize
const country = require('./country').sequelize
const rentals = require('./rentals').sequelize

const con = mysql.createConnection({
    host: "127.0.0.1",
    user: "root",
    password: "Password123$",
    database: "hackaton"
});

con.connect(function(err) {
    if (err) throw err;
    console.log("Connected!");
    var sql = "INSERT INTO country (name, status) VALUES ?";
    var values = [
        ['Afghanistan', 'ture'],
        ['Albania', 'false'],
        ['Algeria', 'true'],
        ['Andorra', 'false'],
        ['Angola', 'false'],
        ['Antigua and Barbuda', 'false'],
        ['Argentina', 'false'],
        ['Armenia', 'false'],
        ['Australia', 'false'],
        ['Austria', 'false'],
        ['Azerbaijan', 'false'],
        ['Bahamas', 'false'],
        ['Bahrain', 'false'],
        ['Bangladesh', 'false'],
        ['Barbados', 'false'],
        ['Belarus', 'true'],
        ['Belgium', 'false'],
        ['Belize', 'false'],
        ['Benin', 'true'],
        ['Bosnia and Herzegovina', 'false'],
        ['Botswana', 'false'],
        ['Brazil', 'false'],
        ['Brunei', 'false'],
        ['Bulgaria', 'false'],
        ['Brazil', 'false'],
        ['Burkina Faso', 'true'],
        ['Burundi', 'false'],
        ['Cabo Verde', 'false'],
        ['Cambodia', 'false'],
        ['Cameroon', 'true'],
        ['Canada', 'false'],
        ['Central African Republic', 'true'],
        ['Chad', 'true'],
        ['Chile', 'false'],
        ['China', 'false'],
        ['Colombia', 'true'],
        ['Comoros', 'false'],
        ['Congo', 'ture'],
        ['Costa Rica', 'false'],
        ['Croatia', 'false'],
        ['Cuba', 'false'],
        ['Cyprus', 'false'],
        ['Czechia', 'false'],
        ['Denmark', 'false'],
        ['Djibouti', 'false'],
        ['Dominica', 'false'],
        ['Dominican Republic', 'false'],
        ['Ecuador', 'false'],
        ['Egypt', 'false'],
        ['El Salvador', 'false'],
        ['Equatorial Guinea', 'false'],
        ['Eritrea', 'false'],
        ['Estonia', 'false'],
        ['Eswatini', 'false'],
        ['Ethiopia', 'true'],
        ['Fiji', 'false'],
        ['Finland', 'false'],
        ['France', 'false'],
        ['Gabon', 'false'],
        ['Gambia', 'false'],
        ['Georgia', 'false'],
        ['Germany', 'false'],
        ['Ghana', 'true'],
        ['Greece', 'false'],
        ['Grenada', 'false'],
        ['Guatemala', 'false'],
        ['Guinea', 'false'],
        ['Guinea-Bissau', 'false'],
        ['Guyana', 'false'],
        ['Haiti', 'false'],
        ['Holy See', 'false'],
        ['Honduras', 'false'],
        ['Hungary', 'false'],
        ['Iceland', 'false'],
        ['India', 'false'],
        ['Indonesia', 'false'],
        ['Iran', 'false'],
        ['Iraq', 'true'],
        ['Ireland', 'false'],
        ['Israel', 'false'],
        ['Italy', 'false'],
        ['Ivory Coast', 'true'],
        ['Jamaica', 'false'],
        ['Japan', 'false'],
        ['Jordan', 'false'],
        ['Kazakhstan', 'false'],
        ['Kenya', 'false'],
        ['Kiribati', 'false'],
        ['Kuwait', 'false'],
        ['Kyrgyzstan', 'false'],
        ['Laos', 'false'],
        ['Latvia', 'false'],
        ['Lebanon', 'false'],
        ['Lesotho', 'false'],
        ['Liberia', 'false'],
        ['Libya', 'true'],
        ['Liechtenstein', 'false'],
        ['Lithuania', 'false'],
        ['Luxembourg', 'false'],
        ['Madagascar', 'false'],
        ['Malawi', 'false'],
        ['Malaysia', 'false'],
        ['Maldives', 'false'],
        ['Mali', 'true'],
        ['Malta', 'false'],
        ['Marshall Islands', 'false'],
        ['Mauritania', 'true'],
        ['Mauritius', 'false'],
        ['Mexico', 'true'],
        ['Micronesia', 'false'],
        ['Moldova', 'false'],
        ['Monaco', 'false'],
        ['Mongolia', 'false'],
        ['Montenegro', 'false'],
        ['Morocco', 'false'],
        ['Mozambique', 'true'],
        ['Myanmar', 'ture'],
        ['Namibia', 'false'],
        ['Nauru', 'false'],
        ['Nepal', 'false'],
        ['Netherlands', 'false'],
        ['New Zealand', 'false'],
        ['Niger', 'true'],
        ['Nigeria', 'true'],
        ['North Korea', 'false'],
        ['North Macedonia', 'false'],
        ['Norway', 'false'],
        ['Oman', 'false'],
        ['Pakistan', 'false'],
        ['Palau', 'false'],
        ['Palestine State', 'false'],
        ['Panama', 'false'],
        ['Papua New Guinea', 'false'],
        ['Paraguay', 'false'],
        ['Peru', 'false'],
        ['Philippines', 'false'],
        ['Poland', 'false'],
        ['Portugal', 'false'],
        ['Qatar', 'false'],
        ['Romania', 'false'],
        ['Russia', 'true'],
        ['Rwanda', 'false'],
        ['Saint Kitts and Nevis', 'false'],
        ['Saint Lucia', 'false'],
        ['Saint Vincent and the Grenadines', 'false'],
        ['Samoa', 'false'],
        ['San Marino', 'false'],
        ['Sao Tome and Principe', 'false'],
        ['Saudi Arabia', 'true'],
        ['Senegal', 'false'],
        ['Serbia', 'false'],
        ['Seychelles', 'false'],
        ['Sierra Leone', 'false'],
        ['Singapore', 'false'],
        ['Slovakia', 'false'],
        ['Slovenia', 'false'],
        ['Solomon Islands', 'false'],
        ['Somalia', 'true'],
        ['South Africa', 'false'],
        ['South Korea', 'false'],
        ['South Sudan', 'true'],
        ['Spain', 'false'],
        ['Sri Lanka', 'false'],
        ['Sudan', 'true'],
        ['Suriname', 'false'],
        ['Sweden', 'false'],
        ['Switzerland', 'false'],
        ['Syria', 'true'],
        ['Tajikistan', 'false'],
        ['Tanzania', 'true'],
        ['Thailand', 'false'],
        ['Timor-Leste', 'false'],
        ['Togo', 'true'],
        ['Tonga', 'false'],
        ['Trinidad and Tobago', 'false'],
        ['Tunisia', 'true'],
        ['Turkey', 'false'],
        ['Turkmenistan', 'false'],
        ['Tuvalu', 'false'],
        ['Uganda', 'true'],
        ['Ukraine', 'true'],
        ['United Arab Emirates', 'true'],
        ['United Kingdom', 'false'],
        ['USA', 'false'],
        ['Uruguay', 'false'],
        ['Uzbekistan', 'false'],
        ['Vanuatu', 'false'],
        ['Venezuela', 'false'],
        ['Vietnam', 'false'],
        ['Yemen', 'true'],
        ['Zambia', 'false'],
        ['Zimbabwe', 'false']
    ];
    con.query(sql, [values], function (err, result) {
        if (err) throw err;
        console.log("Number of records inserted: " + result.affectedRows);
    });
});
